### ISSUE TITLE
Spring boot v3 and later issues

### ISSUE THREAD

**Issue by hedeonH** [bjornvester/wsdl2java-gradle-plugin#23]
When I try to update my spring boot version from 2.7.11 to 3.0.0, I start to get weird exception during executing wsdl2java task .

Execution failed for task ':wsdl2java'.
> A failure occurred while executing com.github.bjornvester.wsdl2java.Wsdl2JavaWorker
   > javax/xml/bind/JAXBException

Unable to load class 'javax.xml.bind.JAXBException'.

**Comment by bjornvester** [comment]
Spring Boot 3 requires using the `jakarta` namespace, and there can be a lot of changes needed to switch from the `javax` namespace. This exception is likely because the plugin generated code using `javax`, but dependencies were updated to `jakarta` so the class no longer exists.

I recently published a new version 2.0 of the plugin that defaults to the `jakarta` dependencies needed for Spring Boot 3.

**Comment by bjornvester** [comment]
Thanks for reporting - I will take a look at the launcher problem tonight.

In the meantime, I think you can get around it by setting the following in the project using wsdl2java:
```
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17) // Or whatever you are using
    }
}
```

**Comment by strelchm** [comment]
thanks much, with `cxfVersion.set("4.0.2")` it's work!
